/**
 * Noms français des exercices du catalogue.
 *
 * Le catalogue source (exercises.v1.json, seed.ts) reste en anglais : c'est ce
 * qui est stocké chez les utilisateurs existants. La traduction se fait à
 * l'affichage et UNIQUEMENT si le nom stocké est encore le nom d'origine du
 * catalogue — un exercice renommé ou créé par l'utilisateur n'est jamais touché.
 *
 * Format : id → [nom anglais d'origine, nom français].
 * Vocabulaire des salles françaises (on garde « squat », « curl », « dips »…).
 */
import type { Exercise } from './types';

export const EXERCISE_NAMES_FR: Readonly<Record<string, readonly [string, string]>> = {
  sq: ['Back Squat', 'Squat barre'],
  fsq: ['Front Squat', 'Squat avant'],
  box_sq: ['Box Squat', 'Squat sur box'],
  pause_sq: ['Pause Squat', 'Squat avec pause'],
  zercher: ['Zercher Squat', 'Squat Zercher'],
  bp: ['Bench Press', 'Développé couché'],
  ibp: ['Incline Bench Press', 'Développé incliné'],
  declinebp: ['Decline Bench Press', 'Développé décliné'],
  floor_press: ['Floor Press', 'Développé au sol'],
  cgbp: ['Close Grip Bench Press', 'Développé couché prise serrée'],
  jm_press: ['JM Press', 'JM press'],
  skull: ['Skull Crushers', 'Barre au front'],
  dl: ['Deadlift', 'Soulevé de terre'],
  rdl: ['Romanian Deadlift', 'Soulevé de terre roumain'],
  sumo: ['Sumo Deadlift', 'Soulevé de terre sumo'],
  rack_pull: ['Rack Pull', 'Soulevé partiel (rack pull)'],
  goodmorning: ['Good Morning', 'Good morning'],
  ohp: ['Overhead Press', 'Développé militaire'],
  pushpress: ['Push Press', 'Push press'],
  snatch: ['Snatch', 'Arraché'],
  powerclean: ['Power Clean', 'Épaulé en puissance'],
  row: ['Barbell Row', 'Rowing barre'],
  pendlay: ['Pendlay Row', 'Rowing Pendlay'],
  tbrow: ['T-Bar Row', 'Rowing T-bar'],
  hipthrust: ['Hip Thrust', 'Hip thrust'],
  dbbp: ['Dumbbell Bench Press', 'Développé couché haltères'],
  dbibp: ['Incline Dumbbell Press', 'Développé incliné haltères'],
  db_fly: ['Dumbbell Fly', 'Écarté haltères'],
  db_ohp: ['Dumbbell Overhead Press', 'Développé épaules haltères'],
  arnold: ['Arnold Press', 'Développé Arnold'],
  latraise: ['Lateral Raise', 'Élévations latérales'],
  rearraise: ['Rear Delt Fly', 'Oiseau'],
  frontraise: ['Front Raise', 'Élévations frontales'],
  db_ext_rot: ['External Rotation', 'Rotation externe haltère'],
  curl: ['Dumbbell Curl', 'Curl haltères'],
  hammercurl: ['Hammer Curl', 'Curl marteau'],
  inclinecurl: ['Incline Dumbbell Curl', 'Curl incliné haltères'],
  conccurl: ['Concentration Curl', 'Curl concentré'],
  zottman: ['Zottman Curl', 'Curl Zottman'],
  rev_curl: ['Reverse Curl', 'Curl prise inversée'],
  ohtriext: ['Overhead Triceps Ext.', 'Extension triceps au-dessus de la tête'],
  kickback: ['Triceps Kickback', 'Kickback triceps'],
  shrug: ['Dumbbell Shrug', 'Shrug haltères'],
  sarow: ['Single Arm Row', 'Rowing unilatéral haltère'],
  pullover: ['Dumbbell Pullover', 'Pull-over haltère'],
  lunges: ['Walking Lunges', 'Fentes marchées'],
  rev_lunge: ['Reverse Lunge', 'Fentes arrière'],
  bss: ['Bulgarian Split Squat', 'Squat bulgare'],
  gobsquat: ['Goblet Squat', 'Squat goblet'],
  stepup: ['Step-up', 'Montées sur banc'],
  slrdl: ['Single Leg RDL', 'Soulevé de terre roumain unijambe'],
  farmerswalk: ["Farmer's Walk", 'Marche du fermier'],
  db_snatch: ['Dumbbell Snatch', 'Arraché haltère'],
  lat: ['Lat Pulldown', 'Tirage vertical'],
  cableRow: ['Seated Cable Row', 'Tirage horizontal assis'],
  strpulldown: ['Straight Arm Pulldown', 'Tirage bras tendus'],
  facepull: ['Face Pull', 'Face pull'],
  upright: ['Upright Row', 'Tirage menton'],
  cableleraise: ['Cable Lateral Raise', 'Élévation latérale poulie'],
  cablebicurl: ['Cable Biceps Curl', 'Curl biceps poulie'],
  triext: ['Triceps Pushdown', 'Extension triceps poulie'],
  fly: ['Cable Fly', 'Écarté poulie'],
  lowfly: ['Low Cable Fly', 'Écarté poulie basse'],
  highfly: ['High Cable Fly', 'Écarté poulie haute'],
  crunch: ['Cable Crunch', 'Crunch poulie'],
  woodchop: ['Wood Chop', 'Bûcheron à la poulie'],
  pallof: ['Pallof Press', 'Pallof press'],
  pull_through: ['Cable Pull-Through', 'Pull-through poulie'],
  cable_glute: ['Cable Glute Kickback', 'Kickback fessier poulie'],
  cable_ext: ['Cable External Rotation', 'Rotation externe poulie'],
  legpress: ['Leg Press', 'Presse à cuisses'],
  hacksquat: ['Hack Squat', 'Hack squat'],
  legcurl: ['Leg Curl', 'Leg curl'],
  legext: ['Leg Extension', 'Leg extension'],
  calfraise: ['Calf Raise', 'Mollets debout'],
  seatedcalf: ['Seated Calf Raise', 'Mollets assis'],
  abductor: ['Hip Abductor', 'Machine abducteurs'],
  adductor: ['Hip Adductor', 'Machine adducteurs'],
  glute_kick: ['Glute Kickback Machine', 'Kickback fessier machine'],
  back_ext: ['Back Extension', 'Extension lombaire'],
  hyper_ext: ['45° Hyperextension', 'Hyperextension à 45°'],
  chest_mach: ['Machine Chest Press', 'Développé pectoraux machine'],
  pecdeck: ['Pec Deck', 'Pec deck'],
  chestRow: ['Chest Supported Row', 'Rowing buste appuyé'],
  machohp: ['Machine Shoulder Press', 'Développé épaules machine'],
  ghd: ['GHD Sit-up', 'Sit-up GHD'],
  nordicham: ['Nordic Hamstring Curl', 'Nordic ischios'],
  preachercurl: ['Preacher Curl', 'Curl pupitre'],
  bike: ['Stationary Bike', "Vélo d'appartement"],
  rower: ['Row Erg', 'Rameur'],
  treadmill: ['Treadmill', 'Tapis de course'],
  elliptical: ['Elliptical', 'Vélo elliptique'],
  pullup: ['Pull-up', 'Tractions'],
  ctb: ['Chest to Bar Pull-up', 'Tractions poitrine à la barre'],
  muscleup: ['Muscle-up', 'Muscle-up'],
  invrow: ['Inverted Row', 'Rowing inversé'],
  ring_row: ['Ring Row', 'Rowing aux anneaux'],
  dip: ['Dip', 'Dips'],
  ring_dip: ['Ring Dip', 'Dips aux anneaux'],
  pushup: ['Push-up', 'Pompes'],
  hspu: ['Handstand Push-up', 'Pompes en équilibre'],
  pistol: ['Pistol Squat', 'Squat pistol'],
  box_jump: ['Box Jump', 'Sauts sur box'],
  jump_squat: ['Jump Squat', 'Squat sauté'],
  burpee: ['Burpee', 'Burpees'],
  sprint: ['Sprint', 'Sprint'],
  jumprope: ['Jump Rope', 'Corde à sauter'],
  plank: ['Plank', 'Gainage'],
  sideplan: ['Side Plank', 'Gainage latéral'],
  hangingLeg: ['Hanging Leg Raise', 'Relevés de jambes suspendu'],
  ttb: ['Toes to Bar', 'Pieds à la barre'],
  dragon_flag: ['Dragon Flag', 'Dragon flag'],
  abwheel: ['Ab Wheel', 'Roue abdominale'],
  deadbug: ['Dead Bug', 'Dead bug'],
  rustwist: ['Russian Twist', 'Rotations russes'],
  l_sit: ['L-sit', 'L-sit'],
  trap_dl: ['Trap Bar Deadlift', 'Soulevé de terre trap bar'],
  landmine_p: ['Landmine Press', 'Développé landmine'],
  landmine_r: ['Landmine Row', 'Rowing landmine'],
  kettleswing: ['Kettlebell Swing', 'Swing kettlebell'],
  kb_press: ['Kettlebell Press', 'Développé kettlebell'],
  kb_snatch: ['Kettlebell Snatch', 'Arraché kettlebell'],
  kb_thruster: ['Kettlebell Thruster', 'Thruster kettlebell'],
  tgu: ['Turkish Get-Up', 'Relevé turc'],
  med_slam: ['Medicine Ball Slam', 'Slam ball'],
  tire_flip: ['Tire Flip', 'Retournement de pneu'],
  yoke_walk: ['Yoke Walk', 'Marche au joug'],
  sandbag: ['Sandbag Carry', 'Portage de sac de sable'],
  log_press: ['Log Press', 'Développé tronc'],
  assault_bike: ['Assault Bike', 'Assault bike'],
  battlerope: ['Battle Rope', 'Cordes ondulatoires'],
  sled: ['Sled Push', 'Poussée de traîneau'],
};

/** Nom affiché : français si le nom stocké est celui d'origine du catalogue. */
export function exerciseDisplayName(id: string, storedName: string): string {
  const entry = EXERCISE_NAMES_FR[id];
  if (entry && storedName.trim() === entry[0]) return entry[1];
  return storedName;
}

export function localizeExercises(list: readonly Exercise[]): Exercise[] {
  return list.map((ex) => {
    const name = exerciseDisplayName(ex.id, ex.name);
    return name === ex.name ? ex : { ...ex, name };
  });
}
