-- ============================================================================
-- Migration 008 : AI Coach usage log (rate limit)
-- ============================================================================
-- Trace des requêtes au coach IA pour appliquer un rate limit basique.
-- 10 requêtes glissantes / heure / user (configurable côté Edge Function).
-- ============================================================================

create table if not exists public.ai_coach_usage (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null references auth.users(id) on delete cascade,
  requested_at timestamptz not null default now(),
  prompt_chars int  not null default 0
);

create index if not exists ai_coach_usage_user_time_idx
  on public.ai_coach_usage (user_id, requested_at desc);

alter table public.ai_coach_usage enable row level security;

-- Lecture : un user voit uniquement ses propres requêtes (pour debug front éventuel)
drop policy if exists "own ai_coach_usage read" on public.ai_coach_usage;
create policy "own ai_coach_usage read"
  on public.ai_coach_usage
  for select
  using (auth.uid() = user_id);

-- Insertion : seul l'Edge Function (service_role) écrit ici.
-- Pas de policy pour les clients → écriture refusée par RLS.
